#!/bin/sh
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/InterpolateDM/DM_NLOfromInterpolation_histos_above0p5_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/InterpolateDM/DM_NLOfromInterpolation_histos_below0p5_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit

cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/transfer_factors_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/ADD_histos_above0p5_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/ADD_histos_below0p5_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/DM_EWK_histos_above0p5_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/DM_EWK_histos_below0p5_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/DM_LO_histos_above0p5_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/DM_LO_histos_below0p5_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/DM_NLO_pta130_histos_above0p5_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/DM_NLO_pta130_histos_below0p5_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/ZnnG_histos_above0p5_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/ZnnG_histos_below0p5_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/ZmmG_histos_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/ZeeG_histos_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/WmnG_histos_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
cp /nfs_scratch/jjbuchanan/CMSSW_8_0_26_patch1/src/ControlRegionStudy_clean/WenG_histos_Pt.root /nfs_scratch/jjbuchanan/CMSSW_8_1_0/src/HiggsAnalysis/CombinedLimit/SimultaneousFit
