combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-1d-6.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-1d-6.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-6d-8.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-6d-8.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-4d-4.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-4d-4.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-3d-8.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-3d-8.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-1d-8.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-1d-8.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-3d-4.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-3d-4.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-3d-5.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-3d-5.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-3d-6.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-3d-6.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-1d-5.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-1d-5.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-1d-3.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-1d-3.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-3d-3.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-3d-3.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-2d-3.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-2d-3.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-4d-8.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-4d-8.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-6d-5.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-6d-5.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-6d-4.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-6d-4.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-6d-3.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-6d-3.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-2d-6.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-2d-6.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-2d-5.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-2d-5.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-2d-4.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-2d-4.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-4d-3.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-4d-3.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-2d-8.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-2d-8.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-4d-5.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-4d-5.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-1d-4.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-1d-4.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-4d-6.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-4d-6.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-6d-6.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-6d-6.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-5d-3.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-5d-3.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-5d-6.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-5d-6.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-5d-4.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-5d-4.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-5d-5.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-5d-5.txt
combine -M AsymptoticLimits cards_ADD_Pt/comb_card_ADDmonoPhoton_MD-5d-8.txt -s -1  | while read SRC; do echo $SRC; done &> results_ADD_Pt/scaled_limits_ADDmonoPhoton_MD-5d-8.txt
