combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-10_Mv-100.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-10_Mv-100.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1000_Mv-10000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1000_Mv-10000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1000_Mv-10.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1000_Mv-10.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-500_Mv-500.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-500_Mv-500.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-150_Mv-500.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-150_Mv-500.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-10_Mv-15.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-10_Mv-15.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1_Mv-500.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1_Mv-500.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1_Mv-2000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1_Mv-2000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1_Mv-300.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1_Mv-300.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-10_Mv-10.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-10_Mv-10.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-50_Mv-95.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-50_Mv-95.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-10_Mv-50.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-10_Mv-50.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-150_Mv-295.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-150_Mv-295.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1_Mv-200.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1_Mv-200.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1_Mv-300.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1_Mv-300.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-50_Mv-10000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-50_Mv-10000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-50_Mv-10000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-50_Mv-10000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1000_Mv-10000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1000_Mv-10000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1_Mv-2000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1_Mv-2000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-150_Mv-10000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-150_Mv-10000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-500_Mv-10000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-500_Mv-10000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1_Mv-50.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1_Mv-50.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-10_Mv-50.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-10_Mv-50.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-10_Mv-10000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-10_Mv-10000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1_Mv-100.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1_Mv-100.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-500_Mv-995.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-500_Mv-995.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-150_Mv-200.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-150_Mv-200.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-10_Mv-100.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-10_Mv-100.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-500_Mv-500.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-500_Mv-500.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-150_Mv-10.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-150_Mv-10.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-500_Mv-10000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-500_Mv-10000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1_Mv-20.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1_Mv-20.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1_Mv-1000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1_Mv-1000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-150_Mv-1000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-150_Mv-1000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-150_Mv-500.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-150_Mv-500.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1_Mv-50.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1_Mv-50.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-10_Mv-10000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-10_Mv-10000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1_Mv-200.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1_Mv-200.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1000_Mv-10.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1000_Mv-10.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-50_Mv-200.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-50_Mv-200.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1_Mv-100.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1_Mv-100.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1000_Mv-1995.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1000_Mv-1995.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1_Mv-10000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1_Mv-10000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-50_Mv-300.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-50_Mv-300.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-500_Mv-995.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-500_Mv-995.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-10_Mv-10.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-10_Mv-10.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-50_Mv-10.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-50_Mv-10.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-150_Mv-200.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-150_Mv-200.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-500_Mv-10.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-500_Mv-10.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1_Mv-10000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1_Mv-10000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-500_Mv-2000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-500_Mv-2000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1_Mv-20.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1_Mv-20.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1000_Mv-1000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1000_Mv-1000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-500_Mv-10.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-500_Mv-10.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-50_Mv-300.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-50_Mv-300.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-50_Mv-95.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-50_Mv-95.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-50_Mv-200.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-50_Mv-200.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1_Mv-10.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1_Mv-10.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-150_Mv-10000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-150_Mv-10000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-50_Mv-50.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-50_Mv-50.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-1000_Mv-1000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-1000_Mv-1000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_V_Mx-10_Mv-15.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_V_Mx-10_Mv-15.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-50_Mv-50.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-50_Mv-50.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1_Mv-1000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1_Mv-1000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-150_Mv-295.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-150_Mv-295.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1_Mv-10.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1_Mv-10.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-150_Mv-10.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-150_Mv-10.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-150_Mv-1000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-150_Mv-1000.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-1000_Mv-1995.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-1000_Mv-1995.txt
combine -M AsymptoticLimits cards_LO_Pt/comb_card_DM_LO_AV_Mx-500_Mv-2000.txt -s -1  | while read SRC; do echo $SRC; done &> results_LO_Pt/scaled_limits_DM_LO_AV_Mx-500_Mv-2000.txt
